nodeLinker: node-modules

# The following 3 settings have been recommended to speed up CI time (and are used by redwoodjs)
nmMode: hardlinks-global
enableGlobalCache: true
compressionLevel: 0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
