export const sources = [
  '***REMOVED***', // instacart. overrides the segmentio host.
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
  '***REMOVED***',
]

export const samples = {
  'adlearn-open-platform': ['***REMOVED***'],
  'adobe-analytics': ['***REMOVED***'],
  adroll: ['***REMOVED***'],
  adwords: ['***REMOVED***'],
  alexa: ['***REMOVED***'],
  amplitude: ['***REMOVED***'],
  appboy: ['***REMOVED***'],
  appcues: ['***REMOVED***'],
  appnexus: ['***REMOVED***'],
  aptrinsic: ['***REMOVED***'],
  auryc: ['***REMOVED***'],
  'bing-ads': ['***REMOVED***'],
  blueshift: ['***REMOVED***'],
  bronto: ['***REMOVED***'],
  bugherd: ['***REMOVED***'],
  bugsnag: ['***REMOVED***'],
  chameleon: ['***REMOVED***'],
  chartbeat: ['***REMOVED***'],
  clevertap: ['***REMOVED***'],
  clicky: ['***REMOVED***'],
  comscore: ['***REMOVED***'],
  'crazy-egg': ['***REMOVED***'],
  criteo: ['***REMOVED***'],
  curebit: ['***REMOVED***'],
  'customer.io': ['***REMOVED***'],
  'doubleclick-floodlight': ['***REMOVED***'],
  drip: ['***REMOVED***'],
  elevio: ['***REMOVED***'],
  eloqua: ['***REMOVED***'],
  errorception: ['***REMOVED***'],
  'facebook-pixel': ['***REMOVED***'],
  friendbuy: ['***REMOVED***'],
  fullstory: ['***REMOVED***'],
  'google-adwords-new': ['***REMOVED***'],
  'google-analytics': ['***REMOVED***'],
  'google-cloud-pubsub': ['***REMOVED***'],
  'google-tag-manager': ['***REMOVED***'],
  gosquared: ['***REMOVED***'],
  heap: ['***REMOVED***'],
  'hello-bar': ['***REMOVED***'],
  hindsight: ['***REMOVED***'],
  hotjar: ['***REMOVED***'],
  hubspot: ['***REMOVED***'],
  improvely: ['***REMOVED***'],
  inspectlet: ['***REMOVED***'],
  intercom: ['***REMOVED***'],
  iterable: ['***REMOVED***'],
  'keen-io': ['***REMOVED***'],
  kissmetrics: ['***REMOVED***'],
  klaviyo: ['***REMOVED***'],
  'linkedin-insight-tag': ['***REMOVED***'],
  livechat: ['***REMOVED***'],
  'lucky-orange': ['***REMOVED***'],
  lytics: ['***REMOVED***'],
  madkudu: ['***REMOVED***'],
  'marketo-v2': ['***REMOVED***'],
  mediamath: ['***REMOVED***'],
  mixpanel: ['***REMOVED***'],
  moengage: ['***REMOVED***'],
  monetate: ['***REMOVED***'],
  mouseflow: ['***REMOVED***'],
  mousestats: ['***REMOVED***'],
  olark: ['***REMOVED***'],
  optimizely: ['***REMOVED***'],
  outbound: ['***REMOVED***'],
  pardot: ['***REMOVED***'],
  parsely: ['***REMOVED***'],
  pendo: ['***REMOVED***'],
  'perfect-audience': ['***REMOVED***'],
  pingdom: ['***REMOVED***'],
  'pinterest-tag': ['***REMOVED***'],
  piwik: ['***REMOVED***'],
  qualaroo: ['***REMOVED***'],
  quantcast: ['***REMOVED***'],
  'quora-conversion-pixel': ['***REMOVED***'],
  rollbar: ['***REMOVED***'],
  saasquatch: ['***REMOVED***'],
  satismeter: ['***REMOVED***'],
  sentry: ['***REMOVED***'],
  shareasale: ['***REMOVED***'],
  simplereach: ['***REMOVED***'],
  snapengage: ['***REMOVED***'],
  spinnakr: ['***REMOVED***'],
  taplytics: ['***REMOVED***'],
  totango: ['***REMOVED***'],
  'track-js': ['***REMOVED***'],
  'tv-squared': ['***REMOVED***'],
  'twitter-ads': ['***REMOVED***'],
  vero: ['***REMOVED***'],
  'visual-website-optimizer': ['***REMOVED***'],
  webengage: ['***REMOVED***'],
  wishpond: ['***REMOVED***'],
  woopra: ['***REMOVED***'],
  wootric: ['***REMOVED***'],
  'yandex-metrica': ['***REMOVED***'],
  yellowhammer: ['***REMOVED***'],
  zopim: ['***REMOVED***'],
}
