env:
  SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials,ecr,npm-publish'
  SEGMENT_BUILDKITE_IMAGE: 'analytics-next-ci-agent'
steps:
  - label: ':hammer: Build Libraries'
    key: build
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - make ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']
          save: true

  - label: ':hammer: QA'
    key: qa
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - yarn add --dev playwright
      - echo "+++ Running QA Tests :pray:"
      - make test-qa
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']

  - label: ':lock: Snyk'
    agents:
      queue: v1
    command: 'bk-snyk'

  - label: ':hammer: Destinations QA'
    key: destinations
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - yarn add --dev playwright
      - echo "+++ Running Destinations QA Tests :pray:"
      - make test-qa-destinations
    soft_fail:
      - exit_status: '*'
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']

  # Auto deploys branches
  - label: ':rocket: Release Branch'
    branches: '!master !v*'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - make build-prod
      - NODE_ENV=production bash ./scripts/release.sh
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']

  # Deploy and NPM publish releases
  - label: ':rocket: Release Production'
    depends_on: [build]
    branches: 'v*'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - make build-prod
      - NODE_ENV=production RELEASE=true bash ./scripts/release.sh
      - npm publish
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']
