env:
  SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials,ecr,npm-publish'
  SEGMENT_BUILDKITE_IMAGE: 'analytics-next-ci-agent'
steps:
  - label: '[Monorepo] QA'
    key: monorepo
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "+++ Run tests"
      - yarn constraints
      - yarn run test:scripts
      - yarn run test:check-dts
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Browser] Lint + Test'
    key: browser-lint-test
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - yarn run -T browser exec make ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']
          save: true

  - label: '[Browser] QA / E2E :perfection:'
    key: qa
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run QA Tests :pray:"
      - yarn run -T browser exec make test-qa
    retry:
      automatic:
        - exit_status: '*'
          limit: 2
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Browser] Integration Tests :perfection:'
    key: browser-integ
    agents:
      queue: v1
    commands:
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn install --immutable
      - PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers npx playwright install
      - echo "+++ Run Browser integration tests :pray:"
      - PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers yarn turbo run --filter=browser-integration-tests test
    retry:
      automatic:
        - exit_status: '*'
          limit: 2
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Core] Lint + Test'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "--- Build bundles"
      - yarn run -T core . build
      - echo "+++ Run tests"
      - yarn run -T core lint
      - yarn run -T core test
      - yarn turbo run --filter=core-integration-tests lint
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Consent] Lint + Test'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "--- Build bundles"
      - yarn turbo run --filter='./packages/consent/*' build
      - echo "+++ Run Lint"
      - yarn turbo run --filter='./packages/consent/*' lint
      - echo "+++ Run Tests"
      - yarn turbo run --filter='./packages/consent/*' test
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: ':thisisfine: [Browser] Destinations QA / E2E'
    key: destinations
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run Destinations QA Tests :pray:"
      - yarn run -T browser exec make test-qa-destinations
    soft_fail:
      - exit_status: '*'
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Browser] Release to CDN :rocket:'
    branches: '!v* !@segment/* !publish-test'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "+++ Release to CDN"
      - yarn run -T browser release:cdn
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: '[Examples] Lint + Test :hammer:'
    key: examples
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "--- Build bundles"
      - yarn turbo run --filter='./examples/*' build
      - echo "+++ Run tests"
      - yarn turbo run --filter='./examples/*' lint
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  # Deploy and NPM publish releases
  - label: '[Browser] Publish Packages to NPM :rocket:'
    if: |
      // Only run when Version Packages PR is merged in
      build.message =~ /^Version Packages/ &&
      build.branch == "master" &&
      build.message !~ /\[skip\]/i
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - git config --global user.name "buildkite-agent"
      - git config --global user.email "buildkite-agent@segment.com"
      - echo "--- Install dependencies"
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable
      - echo "+++ Release packages"
      - yarn release
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['.yarn/cache/']

  - label: 'Snyk :lock:'
    agents:
      queue: v1
    command: 'bk-snyk'

