env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr,npm-publish"
  SEGMENT_BUILDKITE_IMAGE: "analytics-next-ci-agent"
steps:
  - label: "[Monorepo] QA"
    key: monorepo
    agents:
      queue: v1
    commands:
      - yarn constraints

  - label: "[Browser] Lint + Test"
    key: build
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - yarn workspace @segment/analytics-next exec make ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]
          save: true

  - label: "[Browser] QA / E2E :perfection:"
    key: qa
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run QA Tests :pray:"
      - yarn workspace @segment/analytics-next exec make test-qa
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  - label: "[analytics-node] Lint + Test"
    key: analytics-node-test
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run tests"
      - yarn workspace @segment/analytics-node lint
      - yarn workspace @segment/analytics-node test
      - yarn workspace @segment/analytics-node build
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  - label: ":thisisfine: [Browser] Destinations QA / E2E"
    key: destinations
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run Destinations QA Tests :pray:"
      - yarn workspace @segment/analytics-next exec make test-qa-destinations
    soft_fail:
      - exit_status: "*"
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  # Auto deploys branches
  - label: "[Browser] Release Branch (non-prod) :rocket:"
    branches: "!master !v* !publish-test"
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - yarn workspace @segment/analytics-next exec make build-prod
      - NODE_ENV=production yarn workspace @segment/analytics-next exec bash ./scripts/release.sh
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  - label: "[Examples] Lint + Test :hammer:"
    key: examples
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - yarn install --immutable
      - echo "+++ Run tests"
      - yarn workspace @segment/analytics-next build
      - yarn workspace with-next-js lint
      - yarn workspace with-next-js build
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  # Deploy and NPM publish releases
  - label: "Release / Publish Packages :rocket:"
    if: |
      // Only run when Version Packages PR is merged in
      build.message =~ /^Version Packages/ &&
      build.branch == "master" &&
      build.message !~ /\[skip\]/i
    depends_on: [build]
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - echo "--- Install dependencies"
      - HUSKY=0 yarn install --immutable
      - echo "+++ Release packages"
      - yarn release
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  - label: "Snyk :lock:"
    agents:
      queue: v1
    command: "bk-snyk"
