env:
  SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials,ecr'
  SEGMENT_BUILDKITE_IMAGE: 'analytics-next-ci-agent'

steps:
  - label: ':hammer: Build Libraries'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - make ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']
          save: true

  - label: ':hammer: QA'
    key: 'qa'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - yarn add --dev playwright
      - make test-qa
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']

  - label: ':lock: Snyk'
    agents:
      queue: v1
    command: 'bk-snyk'

  - wait: ~

  - label: ':rocket: Release!'
    depends_on: 'qa'
    branches: 'v*'
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install
      - make release-ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']
