env:
  SEGMENT_CONTEXTS: 'snyk,npm,aws-credentials,ecr'
  SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-node12'
steps:
  - label: ':hammer: Build Server'
    agents:
      queue: v1
    commands: |
      echo '--- Install development dependencies'
      npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      yarn install --frozen-lockfile
      echo '--- Build server'
      yarn build
    artifact_paths:
      - 'dist/**/*'
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']
          save: true

  - wait: ~

  - label: ':clippy: Test'
    agents:
      queue: v1
    commands: |
      echo '--- Lint files'
      yarn lint

      echo '--- Run tests'
      yarn test
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: ['node_modules/']

  - label: ':lock: Snyk'
    agents:
      queue: v1
    command: 'bk-snyk'
