env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr,npm-publish"
  SEGMENT_BUILDKITE_IMAGE: "analytics-next-ci-agent"
steps:
  - label: ":hammer: [Browser] Lint + Test"
    key: build
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - yarn workspace @segment/analytics-next exec make ci
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]
          save: true

  - label: ":hammer: [Examples] Lint + Test"
    key: examples
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - yarn workspace @segment/analytics-next build:dev
      - yarn workspace with-next-js lint
      - echo "+++ Testing build capability :pray"
      - yarn workspace with-next-js build
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]
          save: true

  - label: ":perfection: [Browser] QA / E2E"
    key: qa
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - echo "+++ Running QA Tests :pray:"
      - yarn workspace @segment/analytics-next exec make test-qa
    retry:
      automatic:
        - exit_status: "*"
          limit: 2
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  - label: ":lock: Snyk"
    agents:
      queue: v1
    command: "bk-snyk"

  - label: ":thisisfine: [Browser] Destinations QA / E2E"
    key: destinations
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - echo "+++ Running Destinations QA Tests :pray:"
      - yarn workspace @segment/analytics-next exec make test-qa-destinations
    soft_fail:
      - exit_status: "*"
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  # Auto deploys branches
  - label: ":rocket: [Browser] Release Branch"
    branches: "!master !v*"
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - yarn workspace @segment/analytics-next exec make build-prod
      - NODE_ENV=production yarn workspace @segment/analytics-next exec bash ./scripts/release.sh
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]

  # Deploy and NPM publish releases
  - label: ":rocket: [Browser] Release Production"
    depends_on: [build]
    branches: "v*"
    agents:
      queue: v1
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --immutable
      - yarn workspace @segment/analytics-next exec make build-prod
      - NODE_ENV=production RELEASE=true yarn workspace @segment/analytics-next exec bash ./scripts/release.sh
      - yarn workspace @segment/analytics-next exec npm publish
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v2.0.0:
          key: "v1.1-cache-dev-{{ checksum 'yarn.lock' }}"
          paths: [".yarn/cache/"]
