name: CI
on:
  push:
env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
jobs:
  analytics-node:
    name: 'analytics-node QA (Node.js v${{ matrix.node-version }})'
    runs-on: ubuntu-latest-large
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - name: Turbo cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - run: yarn turbo run --filter='./packages/node*' lint
      - run: COVERAGE=true yarn turbo run --filter='./packages/node*' test
      - run: yarn turbo run --filter='./packages/node-integration-tests' test:perf-and-durability
      - uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac  # v5
        with:
          fail_ci_if_error: true
          flags: node
          directory: ./packages/node/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
  analytics-node-cf-workers:
    name: 'analytics-node QA (Cloudflare Workers)'
    runs-on: ubuntu-latest-large
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - name: Turbo cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - run: yarn turbo run --filter='./packages/node-integration-tests' test:cloudflare-workers
