name: Markdown Links Check
on:
  schedule:
    # Runs once every 3 days
    - cron: "0 0 */3 * *"
jobs:
  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/workflows/md-link-check.config.json"
