name: Markdown Links Check
on:
  schedule:
    # Runs once every 3 days
    - cron: "0 0 */3 * *"
jobs:
  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest-large
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089  # master
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368  # v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".github/workflows/md-link-check.config.json"
